### PR TITLE
Fix directory permissions for serving locally

### PR DESCRIPTION
**Pull request by pRizz**
Add execute and remove group/public write recursively to all directories. Add Webstorm to gitignore

### CODE REVIEW

**Comment by Joohansson** [comment]
Please explain what that does. You added .idea to the gitignore file, what does that do?
And you included keytools.zip in the PR, why?

**Comment by pRizz** [comment]
Gotcha, I figured it was auto generated. The problem is that certain http servers may fail trying to serve the files in the zip because they don’t have the proper permissions to be read by the http server. I would recommend, before zipping to recursively modify the permissions to allow execute on the directories. I can look into this.

**Comment by Joohansson** [comment]
Ok thanks, now I understand. It sounds like a valid approach. It should be in the package.json on the line: "build": "react-app-rewired build && gulp zip". Between the build and gulp zip. Maybe there is an npm package available that does that. People have thought about most things. Please let me know if you find something, and probably best make a new PR in that case.

**Comment by Joohansson** [comment]
Ok so I will from now on serve the zip via the gh-pages branch instead of generating it myself. That will not only save git space but also make future PRs easier. I cleaned the zip from git history, that's why this PR is now completely broken. However, I'm not sure how to solve the permissions now. Do you think it's still possible? It's the build folder that is mirrored to gh-pages.

**Comment by pRizz** [comment]
Your code has good permissions now 🍻

**Comment by Joohansson** [comment]
I haven't done any changes but compiling using linux now instead of windows, could be that.

**Pull request closed without merging**
